edition = "2021"

wrap_comments = true
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true

max_width = 120
fn_single_line = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
